### ISSUE TITLE
New Super Mario Bros 2 crashing with luma 10.0 and 10.0.1

### ISSUE THREAD

**Issue by meepingsnesroms** [LumaTeam/Luma3DS#1281]
The game is just playing normally and then it crashed with errDisp:
![IMG_20190703_183544831](https://user-images.githubusercontent.com/1220805/60633993-0a16e680-9dc2-11e9-9ac6-323833a91b6b.jpg)
I never had this issue with luma 9.1 but also dident play the game much there so I may have just never triggered it, it did happen twice in 2 days though and I played < 2 hours each time.

This crash has happened twice now causing loss of save data both times.
First time was on 10.0, second was on 10.0.1, both give the same error.

Firmware 11.10.0-43U, New 2DS.

**Comment by meepingsnesroms** [comment]
Also not using any cheats or custom modules, just luma and the game.

**Comment by lucasaf04** [comment]
Same with Super Mario Maker in old 3DS

**Comment by GlazedBelmont** [comment]
Ok, so @lucasaf04 , are you sure its the exact same error screen and what were you doing right before it crashed?

**Comment by GlazedBelmont** [comment]
and can you also test on luma 9.1 please

**Comment by fincs** [comment]
Is this a cartridge, or a digitally purchased game? If the latter, would it be possible for you to check your SD card for errors, or try a different SD card?

**Comment by GlazedBelmont** [comment]
this seems to be an issue related to luma 10 itself , errdisp crash screens will not show properly and appears fucked up.

**Comment by lucasaf04** [comment]
Yes, same error. @GlaZedBelmont 
And I was just playing.

**Comment by GlazedBelmont** [comment]
yeah, as I said, you two are actually getting normal errdisp errors if we call them so, but the errdisp error screens probably broke with luma 10+

**Comment by brunocar** [comment]
im getting similar errors when booting up heroes of ruin, its also an errdisp

**Comment by TuxSH** [comment]
Should probably be fixed by latest commits?

**Comment by CedarCoder1** [comment]
I still experience random crashes in the older versions and latest versions of luma3ds. In the latest releases the crash shuts the system down and you'll need to replace all the luma3ds files for the handheld to boot again.

I tested versions 11, 12.0.1, 13.0.1, 13.1.2
11 sometimes gives the error and allows for a reboot. I haven't seen the other versions give that crash error. Might be due to how random it is I guess.
