### ISSUE TITLE
Screen init has been fixed

### ISSUE THREAD

**Issue by profi200** [LumaTeam/Luma3DS#1396]
I have spend some time reverse engineering GSP code to finally fix this. Corgi3DS was also a huge help. It mostly boils down to waiting for MCU events 24-29 and waiting for the LCDs to indicate they are ready. Not doing so causes random screen init problems like we have been plagued by for years. The fix only works if all homebrew bootloaders respect it because turning screens off for example and booting a FIRM too early can make screen init fail in the booted FIRM.

Because i'm not sure if/how IRQ stuff should be integrated into Luma (which is needed to wait for MCU events) i decided to make an issue instead of a PR. Hopefully that doesn't come across as lazy or something.

Here is the code:
https://github.com/profi200/open_agb_firm/blob/master/source/arm11/hardware/gfx.c#L118

**Comment by TuxSH** [comment]
Wow, I certainly didn't expect that, thank you very much!

It's not going into this release but into the next one, for which I have planned to have an IRQ handler for the Arm11 (to prevent MCU i2c polling)

**Comment by profi200** [comment]
No worries. It will do for now. When writing that GBA stuff i had screen init problems once more on my N3DS XL so i thought it's time to finally fix this.

**Comment by hunt-young1** [comment]
Is it just me or does that link not work anymore

**Comment by urherenow** [comment]
Perhaps because this is nearly 3 years old?

**Comment by profi200** [comment]
The line you are searching for is now here: https://github.com/profi200/libn3ds/blob/master/source/arm11/drivers/gfx.c#L66

This new driver design has been stable for me and the ported version in GodMode9 is doing well too.

**Comment by justamii** [comment]
And what i have to do with this line? i have the same problem with the screen flicking with the splash screen on

**Comment by NightScript370** [comment]
> And what i have to do with this line? i have the same problem with the screen flicking with the splash screen on

These lines of code making up a "block of code" is more so pointed here for the developers of the software, who would port over the code from libn3ds/GodMode9 to Luma3DS. It is not beneficial to an end-user.

**Comment by Kyokuo** [comment]
So is there any proper workaround for fixing this issue as it perssists a couple years now? Using godmode9 how did u port the fix? Looking at the libn3ds could I maybe compile and run it replacing the splash or is there anything in particular that solves this ? Whatever that may be I really want to use some custom splashes even if it means writing or contributing to the software or some sepparate event handler

**Comment by profi200** [comment]
The code base Luma uses right now is missing some things like interrupts that are needed for this so i doubt libn3ds will help here (it's in a pretty messy state so i would assume they don't want to use it anyway). If i recall correctly an attempt was made to port this years ago but it didn't work as expected. GodMode9 has some basic interrupt support at least on ARM11 so it works good enough.

**Comment by Kyokuo** [comment]
Does it now? I have been out of the loop for quite some time so I wasn't aware of this. So is it already implemented with godmode9 or you're talking about the possibility of implementing it using it?

**Comment by profi200** [comment]
It has been in GodMode9 for years. Not in Luma3DS yet.

**Comment by panchicleto** [comment]
How do I get into the code to change the variants?

**Comment by profi200** [comment]
You don't. Luma and my codebase are not really compatible and there is some work needed to port that.

I should probably use commit based links from now on. This is the latest one.
https://github.com/profi200/libn3ds/blob/d18c577e10589a52f23b7dafbbfd98c8764529ae/source/arm11/drivers/gfx.c#L303

**Comment by Meckload** [comment]
Hi! Just to double check as an end-user with this issue (flickering touch screen). We still wait for this to be implemented in an official Luma update, right?

**Comment by TuxSH** [comment]
It'll get fixed when it does. This requires a full rewrite of the boot loader component and I don't want to mess this up

**Comment by profi200** [comment]
The way Luma works right now makes this tricky. Specifically the wait for MCU events but i think polling the GPIO would work.

**Comment by guildmarm** [comment]
I know this issue is still being worked on. Thankfully on my system it stabilizes and stops flickering after about a minute or two after boot. I'm curious though if there's any temporary solution in the mean time. Also, do we foresee any long term issues for IPS displays facing this issue if splash screens are left enabled and the flicker is left alone?

**Comment by profi200** [comment]
Only known workaround is disabling splash screens. If i remember correctly TuxSH attempted to port my code but it didn't really work for him. The codebases are too different. My code requires interrupt support and Luma doesn't have that.

**Comment by celloh123** [comment]
having the ghosting + flickering issue even while splash screens are disabled on luma 13.3.2

**Comment by user18081972** [comment]
Wasnt this fixed in v13.3.3 ?

**Comment by TuxSH** [comment]
> Wasnt this fixed in v13.3.3 ?

Correct

**Comment by N1nj4Ch1cken** [comment]
> > Wasnt this fixed in v13.3.3 ?
> 
> Correct

I updated my N3DS LL with v13.4 and I still get the bottom right screen to flicker on my dual IPS. When I first updated it and enabled the splash (before payloads) it worked. But then I switched it to after payloads and then the flicker came back. Now neither before or after remove the flicker.
