### ISSUE TITLE
How to patch the games?

### ISSUE THREAD

**Issue by acelerador25** [LumaTeam/Luma3DS#524]
I need the steps to patch games in the new 8.0 because I can't play the FE Fates DLC (usa console/eur game/dlc) and this is in general in all games that need to be patched

**Comment by Thelostrune** [comment]
There's an option for "Enable game patching" in the Luma configuration menu.
However, I'm experiencing crashes that might or might not be related to game patching as a whole. Just saying.

**Comment by acelerador25** [comment]
@Thelostrune, people talk (I'm included) that is the first thing that is done to patch (I know that), then go to any game and don't see the patch, in this case the eur DLC from Fates, and what is the new extras that is on the release

**Comment by Sonikato** [comment]
Same here, i cant play my dlc

**Comment by Gudf** [comment]
Did you read the wiki ?

**Comment by acelerador25** [comment]
And you see that is not modified, or I'm wrong @Gudf?

**Comment by Gudf** [comment]
And ? Why would this mean it's false ? As far as I know, the part about game patching is still correct, and the changes are mentioned in the release notes anyway.

**Comment by acelerador25** [comment]
@Gudf, I believe in this case that there is something different in it and we need to see that, and not even see it in the wiki as I suppose it is not updated

**Comment by Red1812** [comment]
I have the same issue. If I activate game patching LayerFS and locale work but FEF cannot read the DLCs. If I deactivate game patching FEF can access the DLCs but I loose locale and LayerFS.
The issue is in Luma 8.0.

**Comment by jonirrings** [comment]
I had the same issue.
jp console and jp game/dlc.
then modify the locale txt to `JPN JP JP 01` solve my problem.
maybe a new spec on language emulation is needed on the wiki.

**Comment by Red1812** [comment]
I have a EUR console EUR game/dlc from eShop, not cart. I tried EUR EN and EUR EN EN 01 and the game still says SD card inaccessible.

**Comment by Red1812** [comment]
I made a new test. I just remove the locale.txt file and keep the romfs. Everything works fine.
So I guess there is something wrong with the locale or we're missing something obvious...

**Comment by jonirrings** [comment]
@Red1812 yes, we miss the `language emulation` spec, with which we can set the appropriate locale text

**Comment by Red1812** [comment]
@jonirrings What do you mean?

**Comment by jonirrings** [comment]
@Red1812 I mean, a detailed spec is needed on what to write in a locale.txt

**Comment by ITZYOBOYkoko** [comment]
I'm playing USA Fire Emblem Echoes DLC and it's not working. I enable game patching in luma config and sdcard>titles>game id>locale.txt>USA EN and still the DLC is not working. 

Did I do something wrong or is it a bug or idk lol?

EDIT:
Tried the language patching and stuff in bootNTR and now everything is working just fine.

**Comment by drzombee** [comment]
have the same prblem.  in luma 7.1  i was patched dlc in luma menu, FE FATS run the DLC but monster hunter GEN dont run and crash. now in luma 8.0 i was patched  the dlc and FE FATES dont read the sd card and MH GEN don run. thanks for read my bad english
EL.PSY.CONGROO.

**Comment by TuxSH** [comment]
Fixed by the latest commit which you can find below.
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1055982/boot.zip)

**Comment by drzombee** [comment]
@TuxSH  , tx bro but dont work 4 me FE FATES still dont work dlc, i was created a new txt EUR ES and patched dlc option in luma

**Comment by ITZYOBOYkoko** [comment]
@TuxSH that boot.zip is working. Can play FF Echoes DLC now. Wow.

**Comment by henrysimon** [comment]
confirm working, weird though my original was 8.1, copy to usb the boot.firm become 8.0, but when i test it's working in awakening (enable patch and set the region is needed)
